# Site settings
title: 'Andrea Buran’s Sitefolio'
author: Andrea Buran
email: hello@andreaburan.com
description: 'Andrea Buran, at your service. I am a well-rounded designer with a focus on user experience and interface design. I design and craft products and services that put people first.'

baseurl: '' # the subpath of your site, e.g. /blog
url: http://www.andreaburan.com # the base hostname & protocol for your site

timezone: Europe/Rome
encoding: utf-8

collections:
  projects:
    output: true
  categories:
    output: true

# Build settings
markdown: kramdown

# Markdown Processors
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..3
