# Site settings
title: "Andrea Buran’s Sitefolio"
author: Andrea Buran
email: hello@andreaburan.com
description: "Feel free to take a look around! / Andrea Buran’s Sitefolio."

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://andreaburan.com" # the base hostname & protocol for your site

timezone: Europe/Rome
encoding: utf-8

collections:
  projects:
    output: true
  categories:
    output: true

# Build settings
markdown: kramdown

# Markdown Processors
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..3